import { Caption, WordTimestamp } from '../types';
import { formatSrtTime, formatVttTime, parseTimeToSeconds } from './time';

/**
 * Exports captions array to SRT formatted text
 */
export function exportToSRT(captions: Caption[]): string {
  const sorted = [...captions].sort((a, b) => a.start - b.start);
  return sorted
    .map((caption, index) => {
      const idx = index + 1;
      const start = formatSrtTime(caption.start);
      const end = formatSrtTime(caption.end);
      const text = caption.text.trim();
      return `${idx}\n${start} --> ${end}\n${text}`;
    })
    .join('\n\n');
}

/**
 * Exports captions array to WebVTT formatted text
 */
export function exportToVTT(captions: Caption[]): string {
  const sorted = [...captions].sort((a, b) => a.start - b.start);
  const cues = sorted
    .map((caption, index) => {
      const idx = index + 1;
      const start = formatVttTime(caption.start);
      const end = formatVttTime(caption.end);
      const text = caption.text.trim();
      return `${idx}\n${start} --> ${end}\n${text}`;
    })
    .join('\n\n');

  return `WEBVTT - Generated by Subtitle Studio\n\n${cues}`;
}

/**
 * Format seconds to ASS timestamp (H:MM:SS.cs)
 */
function formatAssTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100);
  return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cs).padStart(2, '0')}`;
}

/**
 * Exports captions array to Advanced SubStation Alpha (.ass) format with karaoke tags
 */
export function exportToASS(captions: Caption[], fontName: string = 'Arial', primaryColorHex: string = '&H00FFFFFF'): string {
  const sorted = [...captions].sort((a, b) => a.start - b.start);
  
  const header = `[Script Info]
Title: Subtitle Studio Export
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${fontName},32,${primaryColorHex},&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,2,10,10,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text`;

  const dialogueLines = sorted.map((c) => {
    const startStr = formatAssTime(c.start);
    const endStr = formatAssTime(c.end);
    let textStr = c.text.trim();
    if (c.words && c.words.length > 0) {
      textStr = c.words
        .map((w) => {
          const durationCs = Math.max(1, Math.round((w.end - w.start) * 100));
          return `{\\k${durationCs}}${w.word}`;
        })
        .join(' ');
    }
    return `Dialogue: 0,${startStr},${endStr},Default,,0,0,0,,${textStr}`;
  });

  return `${header}\n${dialogueLines.join('\n')}`;
}

/**
 * Exports captions array to plain TXT transcript text
 */
export function exportToTXT(captions: Caption[]): string {
  const sorted = [...captions].sort((a, b) => a.start - b.start);
  return sorted.map((c) => c.text.trim()).join('\n');
}

/**
 * Parses SRT file contents into Caption[]
 */
export function parseSRT(srtContent: string): Caption[] {
  const normalized = srtContent.replace(/\r\n/g, '\n').replace(/\r/g, '\n').trim();
  if (!normalized) return [];

  const blocks = normalized.split(/\n\n+/);
  const captions: Caption[] = [];

  for (const block of blocks) {
    const lines = block.split('\n').map((l) => l.trim()).filter(Boolean);
    if (lines.length < 2) continue;

    let timeLineIdx = 0;
    // Check if line 0 is an index number (1, 2, 3...)
    if (!lines[0].includes('-->') && lines.length > 1 && lines[1].includes('-->')) {
      timeLineIdx = 1;
    }

    const timeLine = lines[timeLineIdx];
    if (!timeLine || !timeLine.includes('-->')) continue;

    const [startStr, endStr] = timeLine.split('-->').map((s) => s.trim());
    const start = parseTimeToSeconds(startStr);
    const end = parseTimeToSeconds(endStr);

    const textLines = lines.slice(timeLineIdx + 1);
    const text = textLines.join(' ').replace(/<[^>]*>/g, '').trim();

    if (text && end > start) {
      const words = generateWordTimestampsForText(text, start, end);
      captions.push({
        id: `cap-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
        start,
        end,
        text,
        words,
      });
    }
  }

  return captions.sort((a, b) => a.start - b.start);
}

/**
 * Parses VTT file contents into Caption[]
 */
export function parseVTT(vttContent: string): Caption[] {
  const normalized = vttContent.replace(/\r\n/g, '\n').replace(/\r/g, '\n').trim();
  if (!normalized) return [];

  // Remove WEBVTT header and NOTE blocks
  const cleanContent = normalized
    .replace(/^WEBVTT[^\n]*\n+/i, '')
    .replace(/NOTE(\s+[\s\S]*?)(\n\n|$)/gi, '');

  const blocks = cleanContent.split(/\n\n+/);
  const captions: Caption[] = [];

  for (const block of blocks) {
    const lines = block.split('\n').map((l) => l.trim()).filter(Boolean);
    if (!lines.length) continue;

    let timeLineIdx = -1;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes('-->')) {
        timeLineIdx = i;
        break;
      }
    }

    if (timeLineIdx === -1) continue;

    const timeLine = lines[timeLineIdx];
    const [startPart, endPartWithSettings] = timeLine.split('-->').map((s) => s.trim());
    const endPart = endPartWithSettings ? endPartWithSettings.split(/\s+/)[0] : '';

    const start = parseTimeToSeconds(startPart);
    const end = parseTimeToSeconds(endPart);

    const textLines = lines.slice(timeLineIdx + 1);
    const text = textLines.join(' ').replace(/<[^>]*>/g, '').trim();

    if (text && end > start) {
      const words = generateWordTimestampsForText(text, start, end);
      captions.push({
        id: `cap-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
        start,
        end,
        text,
        words,
      });
    }
  }

  return captions.sort((a, b) => a.start - b.start);
}

/**
 * Splits caption text into word timestamps evenly across duration if word-level data isn't present
 */
export function generateWordTimestampsForText(text: string, start: number, end: number): WordTimestamp[] {
  const rawWords = text.trim().split(/\s+/).filter(Boolean);
  if (!rawWords.length) return [];

  const duration = Math.max(0.1, end - start);
  const wordDuration = duration / rawWords.length;

  return rawWords.map((word, index) => ({
    id: `w-${index}-${Math.random().toString(36).substring(2, 7)}`,
    word,
    start: Number((start + index * wordDuration).toFixed(3)),
    end: Number((start + (index + 1) * wordDuration).toFixed(3)),
  }));
}
